Repository SnapMine/SnapMine, pull requests merged in 2025-09, with the labels that each got.

#62 refactor block break and add LevelEventPacket
  src/Block/Block.php
  src/Network/Packet/Clientbound/Play/LevelEventPacket.php
  src/Network/Packet/Serverbound/Play/PlayerActionPacket.php
  src/World/Chunk/ChunkSection.php
Labels: refactor

#49 Update/command argument
  .dockerignore
  Dockerfile
  server.php
  src/Artisan.php
  src/Command/ArgumentTypes/ArgumentEntity.php
  src/Command/ArgumentTypes/BrigadierInteger.php
  src/Command/ArgumentTypes/BrigadierString.php
  src/Command/ArgumentTypes/CommandArgumentType.php
  src/Command/Command.php
  src/Command/CommandExecutor.php
  src/Command/CommandManager.php
  src/Command/CommandNode.php
  src/Command/Default/GiveCommand.php
  src/Command/Default/HelpCommand.php
  src/Command/Default/KickCommand.php
  src/Command/Default/SendCommand.php
  src/Command/Default/SpawnCommand.php
  src/Command/Nodes/ArgumentNode.php
  src/Command/Nodes/CommandNode.php
  src/Command/Nodes/LiteralNode.php
  src/Network/Packet/Clientbound/Play/CommandsPacket.php
  src/Network/Packet/Serverbound/Play/ChatCommandPacket.php
  src/Network/Packet/Serverbound/Play/PlayerLoadedPacket.php
  src/Server.php
  src/Utils/Flags.php
Labels: feature, refactor, protocol

#63 Add OpenScreenPacket
  src/Inventory/AnvilInventory.php
  src/Inventory/BeaconInventory.php
  src/Inventory/BrewingStandInventory.php
  src/Inventory/CartographyInventory.php
  src/Inventory/CraftingInventory.php
  src/Inventory/EnchantingInventory.php
  src/Inventory/FurnaceInventory.php
  src/Inventory/GrindstoneInventory.php
  src/Inventory/LoomInventory.php
  src/Inventory/SmithingInventory.php
  src/Inventory/StoneCutterInventory.php
  src/Network/Packet/Clientbound/Play/OpenScreenPacket.php
  src/Network/Packet/Serverbound/Play/UseItemOnPacket.php
Labels: feature, packet
